{% set name = "pytest-asdf-plugin" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_asdf_plugin-{{ version }}.tar.gz
  sha256: 40752a7e296d974fde9bf69305a175409f8f5d0765f41edda42e6eaadb3d7088

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=60
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - asdf
    - pytest >=7

test:
  imports:
    - pytest_asdf_plugin
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/asdf-format/pytest-asdf-plugin
  summary: Pytest plugin for testing ASDF schemas
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - braingram
